### Viendo peticiones

### GET - IES 21
GET https://ies21.edu.ar/

### GET - Usuarios platzi
GET https://69cbcb780b417a19e07b42c1.mockapi.io/api/v1/Productos

### GET - Local 
GET http://localhost:3000/usuarios

### POST -
POST http://localhost:3000/
Content-Type: text/plain

Contenido mas largo

### DELETE
DELETE http://localhost:3000/